=begin
#fraudapi

#Easily and directly scan and block fraudulent security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

module CloudmersiveFrauddetectionApiClient
  VERSION = '2.0.0'
end
