=begin
#fraudapi

#Easily and directly scan and block fraudulent security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveFrauddetectionApiClient::FraudDetectionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FraudDetectionApi' do
  before do
    # run before each test
    @instance = CloudmersiveFrauddetectionApiClient::FraudDetectionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FraudDetectionApi' do
    it 'should create an instance of FraudDetectionApi' do
      expect(@instance).to be_instance_of(CloudmersiveFrauddetectionApiClient::FraudDetectionApi)
    end
  end

  # unit tests for document_detect_fraud
  # AI Fraud Detection for Documents
  # Perform fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [File] :input_file Input document, or photos of a document, to perform fraud detection on
  # @return [FraudDetectionResult]
  describe 'document_detect_fraud test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for document_detect_fraud_advanced
  # Advanced AI Fraud Detection for Documents
  # Perform advanced fraud detection and classification on input document and user context.  Input document formats supported include DOCX, PDF, PNG and JPG.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_email_address User email address for context (optional)
  # @option opts [BOOLEAN] :user_email_address_verified True if the user&#39;s email address was verified (optional)
  # @option opts [File] :input_file Input document, or photos of a document, to perform fraud detection on
  # @return [AdvancedFraudDetectionResult]
  describe 'document_detect_fraud_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
