=begin
#fraudapi

#Easily and directly scan and block fraudulent security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-frauddetection-api-client/api_client'
require 'cloudmersive-frauddetection-api-client/api_error'
require 'cloudmersive-frauddetection-api-client/version'
require 'cloudmersive-frauddetection-api-client/configuration'

# Models
require 'cloudmersive-frauddetection-api-client/models/advanced_fraud_detection_result'
require 'cloudmersive-frauddetection-api-client/models/fraud_detection_result'

# APIs
require 'cloudmersive-frauddetection-api-client/api/fraud_detection_api'

module CloudmersiveFrauddetectionApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveFrauddetectionApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
